/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadLogsRouteImport } from './routes/upload-logs'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AssociationsRouteImport } from './routes/associations'
import { Route as IndexRouteImport } from './routes/index'

const UploadLogsRoute = UploadLogsRouteImport.update({
  id: '/upload-logs',
  path: '/upload-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationsRoute = AssociationsRouteImport.update({
  id: '/associations',
  path: '/associations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/associations': typeof AssociationsRoute
  '/categories': typeof CategoriesRoute
  '/corrections': typeof CorrectionsRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/upload': typeof UploadRoute
  '/upload-logs': typeof UploadLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/associations': typeof AssociationsRoute
  '/categories': typeof CategoriesRoute
  '/corrections': typeof CorrectionsRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/upload': typeof UploadRoute
  '/upload-logs': typeof UploadLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/associations': typeof AssociationsRoute
  '/categories': typeof CategoriesRoute
  '/corrections': typeof CorrectionsRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/upload': typeof UploadRoute
  '/upload-logs': typeof UploadLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/associations'
    | '/categories'
    | '/corrections'
    | '/expenses'
    | '/income'
    | '/insights'
    | '/login'
    | '/rules'
    | '/upload'
    | '/upload-logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/associations'
    | '/categories'
    | '/corrections'
    | '/expenses'
    | '/income'
    | '/insights'
    | '/login'
    | '/rules'
    | '/upload'
    | '/upload-logs'
  id:
    | '__root__'
    | '/'
    | '/associations'
    | '/categories'
    | '/corrections'
    | '/expenses'
    | '/income'
    | '/insights'
    | '/login'
    | '/rules'
    | '/upload'
    | '/upload-logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssociationsRoute: typeof AssociationsRoute
  CategoriesRoute: typeof CategoriesRoute
  CorrectionsRoute: typeof CorrectionsRoute
  ExpensesRoute: typeof ExpensesRoute
  IncomeRoute: typeof IncomeRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  RulesRoute: typeof RulesRoute
  UploadRoute: typeof UploadRoute
  UploadLogsRoute: typeof UploadLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload-logs': {
      id: '/upload-logs'
      path: '/upload-logs'
      fullPath: '/upload-logs'
      preLoaderRoute: typeof UploadLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/associations': {
      id: '/associations'
      path: '/associations'
      fullPath: '/associations'
      preLoaderRoute: typeof AssociationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssociationsRoute: AssociationsRoute,
  CategoriesRoute: CategoriesRoute,
  CorrectionsRoute: CorrectionsRoute,
  ExpensesRoute: ExpensesRoute,
  IncomeRoute: IncomeRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  RulesRoute: RulesRoute,
  UploadRoute: UploadRoute,
  UploadLogsRoute: UploadLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
