-- Combined migration bundle for setting up a fresh Supabase project.
-- Generated by concatenating supabase/migrations/*.sql in chronological order.
-- Paste this whole file into the Supabase SQL editor and run it once.
--
-- Prerequisite: create a private storage bucket named "receipts" first
-- (Storage tab in the Supabase dashboard) — the storage policies below
-- reference it by name and are no-ops until the bucket exists.

BEGIN;

-- ===== 20260622071748_7b382e8e-536e-476f-842d-af31a0042308.sql =====


CREATE TABLE public.associations (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  notes TEXT,
  keywords TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.associations TO anon, authenticated;
GRANT ALL ON public.associations TO service_role;
ALTER TABLE public.associations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read associations" ON public.associations FOR SELECT USING (true);
CREATE POLICY "Public insert associations" ON public.associations FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update associations" ON public.associations FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Public delete associations" ON public.associations FOR DELETE USING (true);

CREATE TABLE public.expenses (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  association_id UUID REFERENCES public.associations(id) ON DELETE SET NULL,
  supplier TEXT,
  expense_date DATE,
  amount NUMERIC(14,2),
  currency TEXT,
  category TEXT,
  file_path TEXT,
  file_mime TEXT,
  raw_extraction JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.expenses TO anon, authenticated;
GRANT ALL ON public.expenses TO service_role;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read expenses" ON public.expenses FOR SELECT USING (true);
CREATE POLICY "Public insert expenses" ON public.expenses FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update expenses" ON public.expenses FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Public delete expenses" ON public.expenses FOR DELETE USING (true);

CREATE INDEX expenses_association_idx ON public.expenses(association_id);
CREATE INDEX expenses_date_idx ON public.expenses(expense_date);


-- ===== 20260622071759_d782e976-fb34-47ad-88ba-0b6adb1768c4.sql =====


CREATE POLICY "Public read receipts" ON storage.objects FOR SELECT USING (bucket_id = 'receipts');
CREATE POLICY "Public upload receipts" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'receipts');
CREATE POLICY "Public update receipts" ON storage.objects FOR UPDATE USING (bucket_id = 'receipts') WITH CHECK (bucket_id = 'receipts');
CREATE POLICY "Public delete receipts" ON storage.objects FOR DELETE USING (bucket_id = 'receipts');


-- ===== 20260623111920_8611cc5e-1762-4f8f-a585-1aab0f6956dc.sql =====


CREATE TABLE public.categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  keywords text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.categories TO anon, authenticated;
GRANT ALL ON public.categories TO service_role;

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Public insert categories" ON public.categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update categories" ON public.categories FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Public delete categories" ON public.categories FOR DELETE USING (true);

INSERT INTO public.categories (name) VALUES
  ('Utilities'), ('Cleaning'), ('Maintenance'), ('Lifts'),
  ('Insurance'), ('Tax'), ('Bank'), ('Supplies'),
  ('Professional Services'), ('Other')
ON CONFLICT (name) DO NOTHING;


-- ===== 20260628000000_upload_logs.sql =====


CREATE TABLE public.upload_logs (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  file_name TEXT NOT NULL,
  file_size INTEGER,
  file_mime TEXT,
  status TEXT NOT NULL CHECK (status IN ('success', 'error')),
  expense_id UUID REFERENCES public.expenses(id) ON DELETE SET NULL,
  error_message TEXT,
  input_tokens INTEGER,
  output_tokens INTEGER,
  estimated_cost_usd NUMERIC(10, 6),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.upload_logs TO anon, authenticated;
GRANT ALL ON public.upload_logs TO service_role;

ALTER TABLE public.upload_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read upload_logs"   ON public.upload_logs FOR SELECT USING (true);
CREATE POLICY "Public insert upload_logs" ON public.upload_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update upload_logs" ON public.upload_logs FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Public delete upload_logs" ON public.upload_logs FOR DELETE USING (true);

CREATE INDEX upload_logs_created_at_idx ON public.upload_logs(created_at DESC);
CREATE INDEX upload_logs_status_idx     ON public.upload_logs(status);


-- ===== 20260629000000_upload_logs_source.sql =====

-- Track how each receipt was submitted: 'upload' (manual) or 'email' (inbound email).
ALTER TABLE public.upload_logs
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'upload'
    CHECK (source IN ('upload', 'email'));

CREATE INDEX IF NOT EXISTS upload_logs_source_idx ON public.upload_logs(source);


-- ===== 20260704000000_extraction_audit_log.sql =====

CREATE TABLE public.extraction_audit_log (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  expense_id UUID NOT NULL REFERENCES public.expenses(id) ON DELETE CASCADE,
  file_name TEXT,

  -- Extracted values (post Phase 1 / Phase 4, whichever ran last)
  extracted_supplier TEXT,
  extracted_expense_date TEXT,
  extracted_amount NUMERIC,
  extracted_currency TEXT,
  extracted_category TEXT,
  extracted_association_id UUID,

  -- Which pipeline phase produced the final result
  phase TEXT NOT NULL,  -- "llm_extraction" | "llm_recheck"

  -- Phase 2: deterministic validation results (JSON array of ValidationError, null if none)
  validation_errors JSONB,
  validation_warnings JSONB,

  -- Phase 3: rule-based association matching results
  association_match_confidence NUMERIC(4, 3),  -- 0.0 to 1.0
  association_match_signals TEXT[],

  -- LLM usage (cumulative across phase 1 + phase 4 re-check, if it ran)
  llm_model TEXT,
  input_tokens INTEGER,
  output_tokens INTEGER,
  estimated_cost_usd NUMERIC(10, 6),

  -- Reasoning and full trace
  extraction_reasoning TEXT,
  pipeline_trace JSONB,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.extraction_audit_log TO anon, authenticated;
GRANT ALL ON public.extraction_audit_log TO service_role;

ALTER TABLE public.extraction_audit_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read extraction_audit_log"   ON public.extraction_audit_log FOR SELECT USING (true);
CREATE POLICY "Public insert extraction_audit_log" ON public.extraction_audit_log FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update extraction_audit_log" ON public.extraction_audit_log FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Public delete extraction_audit_log" ON public.extraction_audit_log FOR DELETE USING (true);

CREATE INDEX extraction_audit_log_expense_id_idx ON public.extraction_audit_log(expense_id);
CREATE INDEX extraction_audit_log_phase_idx ON public.extraction_audit_log(phase);
CREATE INDEX extraction_audit_log_created_at_idx ON public.extraction_audit_log(created_at DESC);


-- ===== 20260704010000_learning_loop.sql =====

-- Phase 2: human-in-the-loop learning (see ADK-inspired extraction plan)

CREATE TABLE public.expense_corrections (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  expense_id UUID NOT NULL REFERENCES public.expenses(id) ON DELETE CASCADE,
  field TEXT NOT NULL,
  original_value TEXT,
  corrected_value TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.expense_corrections TO anon, authenticated;
GRANT ALL ON public.expense_corrections TO service_role;

ALTER TABLE public.expense_corrections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read expense_corrections"   ON public.expense_corrections FOR SELECT USING (true);
CREATE POLICY "Public insert expense_corrections" ON public.expense_corrections FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update expense_corrections" ON public.expense_corrections FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Public delete expense_corrections" ON public.expense_corrections FOR DELETE USING (true);

CREATE INDEX expense_corrections_expense_id_idx ON public.expense_corrections(expense_id);

CREATE TABLE public.association_rules (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  supplier_pattern TEXT NOT NULL,
  association_id UUID NOT NULL REFERENCES public.associations(id) ON DELETE CASCADE,
  source_expense_id UUID REFERENCES public.expenses(id) ON DELETE SET NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (supplier_pattern, association_id)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.association_rules TO anon, authenticated;
GRANT ALL ON public.association_rules TO service_role;

ALTER TABLE public.association_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read association_rules"   ON public.association_rules FOR SELECT USING (true);
CREATE POLICY "Public insert association_rules" ON public.association_rules FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update association_rules" ON public.association_rules FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Public delete association_rules" ON public.association_rules FOR DELETE USING (true);

CREATE INDEX association_rules_active_idx ON public.association_rules(active);


-- ===== 20260705000000_duplicate_detection_and_category_rules.sql =====

-- Feature: duplicate-receipt detection
ALTER TABLE public.extraction_audit_log
  ADD COLUMN possible_duplicate_of UUID REFERENCES public.expenses(id) ON DELETE SET NULL;

CREATE INDEX extraction_audit_log_possible_duplicate_of_idx
  ON public.extraction_audit_log(possible_duplicate_of);

-- Feature: category learned rules (mirrors association_rules)
CREATE TABLE public.category_rules (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  supplier_pattern TEXT NOT NULL,
  category TEXT NOT NULL,
  source_expense_id UUID REFERENCES public.expenses(id) ON DELETE SET NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (supplier_pattern, category)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.category_rules TO anon, authenticated;
GRANT ALL ON public.category_rules TO service_role;

ALTER TABLE public.category_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read category_rules"   ON public.category_rules FOR SELECT USING (true);
CREATE POLICY "Public insert category_rules" ON public.category_rules FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update category_rules" ON public.category_rules FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Public delete category_rules" ON public.category_rules FOR DELETE USING (true);

CREATE INDEX category_rules_active_idx ON public.category_rules(active);


-- ===== 20260706000000_ledger_line_items.sql =====

-- Support multi-line ledger receipts: multiple expenses generated from a
-- single uploaded file, grouped together and ordered by their position in
-- the source document.
ALTER TABLE public.expenses
  ADD COLUMN ledger_group_id uuid NULL,
  ADD COLUMN source_line_index integer NULL;

CREATE INDEX expenses_ledger_group_id_idx ON public.expenses (ledger_group_id);


-- ===== 20260710153629_reference_number.sql =====

-- Support extracting an invoice/receipt/reference number from documents.
ALTER TABLE public.expenses
  ADD COLUMN reference_number text NULL;

ALTER TABLE public.extraction_audit_log
  ADD COLUMN extracted_reference_number text NULL;


-- ===== 20260711000000_backfill_duplicate_detection_and_category_rules.sql =====

-- Backfill: 20260705000000_duplicate_detection_and_category_rules.sql was never
-- applied to this database, leaving extraction_audit_log.possible_duplicate_of
-- and the category_rules table missing. Written idempotently so it's safe to
-- run even if some pieces already exist.

ALTER TABLE public.extraction_audit_log
  ADD COLUMN IF NOT EXISTS possible_duplicate_of UUID REFERENCES public.expenses(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS extraction_audit_log_possible_duplicate_of_idx
  ON public.extraction_audit_log(possible_duplicate_of);

CREATE TABLE IF NOT EXISTS public.category_rules (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  supplier_pattern TEXT NOT NULL,
  category TEXT NOT NULL,
  source_expense_id UUID REFERENCES public.expenses(id) ON DELETE SET NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (supplier_pattern, category)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.category_rules TO anon, authenticated;
GRANT ALL ON public.category_rules TO service_role;

ALTER TABLE public.category_rules ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'category_rules' AND policyname = 'Public read category_rules') THEN
    CREATE POLICY "Public read category_rules"   ON public.category_rules FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'category_rules' AND policyname = 'Public insert category_rules') THEN
    CREATE POLICY "Public insert category_rules" ON public.category_rules FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'category_rules' AND policyname = 'Public update category_rules') THEN
    CREATE POLICY "Public update category_rules" ON public.category_rules FOR UPDATE USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'category_rules' AND policyname = 'Public delete category_rules') THEN
    CREATE POLICY "Public delete category_rules" ON public.category_rules FOR DELETE USING (true);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS category_rules_active_idx ON public.category_rules(active);



COMMIT;
